remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Material constraints enabling human cognition (MatCo)
description: Using novel insights from human neurobiology translated into mathematically exact computational models to find new answers to long-standing questions in cognitive science, linguistics and philosophy.
